In [1]:
from bayesml import linearregression
import numpy as np

In [2]:
gen_model = linearregression.GenModel(c_degree=2,seed=1)
gen_model.gen_params()
x,y = gen_model.gen_sample(sample_size=10)

In [3]:
x

array([[-1.30315723,  1.        ],
       [ 0.44637457,  1.        ],
       [ 0.5811181 ,  1.        ],
       [ 0.2941325 ,  1.        ],
       [ 0.54671299,  1.        ],
       [-0.16290995,  1.        ],
       [ 0.59884621,  1.        ],
       [-0.29245675,  1.        ],
       [-0.25719224,  1.        ],
       [-0.27560291,  1.        ]])

In [4]:
y

array([ 0.2572364 , -1.94423406, -1.04368096,  0.38357047,  0.34505834,
        0.39602445,  1.00377535,  2.13152772, -0.95851449, -0.26413351])

In [5]:
print(gen_model.get_params())

{'theta_vec': array([0.79316636, 0.31899438]), 'tau': 1.0730290263725388}


In [6]:
learn_model = linearregression.LearnModel(c_degree=2)
learn_model.update_posterior(x,y)

In [7]:
learn_model.calc_pred_dist(x)

In [8]:
print(learn_model.get_p_params())

{'p_m': array([ 0.42714721, -0.10239176, -0.14317522, -0.05631194, -0.13276166,
        0.08202323, -0.14854107,  0.12123377,  0.1105601 ,  0.11613254]), 'p_lambda': array([0.59162764, 0.78326394, 0.76197179, 0.80126906, 0.76783858,
       0.80909011, 0.75884207, 0.7982456 , 0.80173672, 0.79996311]), 'p_nu': array([12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])}


In [9]:
learn_model.make_prediction(loss='KL')

In [10]:
p_params_batch = learn_model.get_p_params()

In [11]:
p_params_seq = []
for i in range(10):
    learn_model.calc_pred_dist(x[i])
    p_params_seq.append(learn_model.get_p_params())


In [12]:
p_params_seq

[{'p_m': array([0.42714721]),
  'p_lambda': array([0.59162764]),
  'p_nu': array([12.])},
 {'p_m': array([-0.10239176]),
  'p_lambda': array([0.78326394]),
  'p_nu': array([12.])},
 {'p_m': array([-0.14317522]),
  'p_lambda': array([0.76197179]),
  'p_nu': array([12.])},
 {'p_m': array([-0.05631194]),
  'p_lambda': array([0.80126906]),
  'p_nu': array([12.])},
 {'p_m': array([-0.13276166]),
  'p_lambda': array([0.76783858]),
  'p_nu': array([12.])},
 {'p_m': array([0.08202323]),
  'p_lambda': array([0.80909011]),
  'p_nu': array([12.])},
 {'p_m': array([-0.14854107]),
  'p_lambda': array([0.75884207]),
  'p_nu': array([12.])},
 {'p_m': array([0.12123377]),
  'p_lambda': array([0.7982456]),
  'p_nu': array([12.])},
 {'p_m': array([0.1105601]),
  'p_lambda': array([0.80173672]),
  'p_nu': array([12.])},
 {'p_m': array([0.11613254]),
  'p_lambda': array([0.79996311]),
  'p_nu': array([12.])}]

In [13]:
p_params_batch

{'p_m': array([ 0.42714721, -0.10239176, -0.14317522, -0.05631194, -0.13276166,
         0.08202323, -0.14854107,  0.12123377,  0.1105601 ,  0.11613254]),
 'p_lambda': array([0.59162764, 0.78326394, 0.76197179, 0.80126906, 0.76783858,
        0.80909011, 0.75884207, 0.7982456 , 0.80173672, 0.79996311]),
 'p_nu': array([12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])}

In [14]:
for i in range(10):
    if p_params_batch['p_m'][i] != p_params_seq[i]['p_m']:
        print('Error in p_m')
    if not np.isclose(p_params_batch['p_lambda'][i],p_params_seq[i]['p_lambda']):
        print('Error in p_lambda')    

In [15]:
[{'p_m': 0.42714721051663723, 'p_lambda': 0.5916276394259316, 'p_nu': 12.0},
 {'p_m': -0.10239176155884983, 'p_lambda': 0.7832639359232484, 'p_nu': 12.0},
 {'p_m': -0.1431752164114424, 'p_lambda': 0.7619717896431002, 'p_nu': 12.0},
 {'p_m': -0.05631194060649679, 'p_lambda': 0.8012690608119697, 'p_nu': 12.0},
 {'p_m': -0.13276165859089117, 'p_lambda': 0.7678385849077702, 'p_nu': 12.0},
 {'p_m': 0.08202323328694752, 'p_lambda': 0.8090901115344494, 'p_nu': 12.0},
 {'p_m': -0.1485410658906876, 'p_lambda': 0.7588420653498217, 'p_nu': 12.0},
 {'p_m': 0.12123376991501882, 'p_lambda': 0.7982456026015521, 'p_nu': 12.0},
 {'p_m': 0.1105600956685007, 'p_lambda': 0.8017367211580925, 'p_nu': 12.0},
 {'p_m': 0.11613253763727473, 'p_lambda': 0.7999631073472214, 'p_nu': 12.0}]

[{'p_m': 0.42714721051663723, 'p_lambda': 0.5916276394259316, 'p_nu': 12.0},
 {'p_m': -0.10239176155884983, 'p_lambda': 0.7832639359232484, 'p_nu': 12.0},
 {'p_m': -0.1431752164114424, 'p_lambda': 0.7619717896431002, 'p_nu': 12.0},
 {'p_m': -0.05631194060649679, 'p_lambda': 0.8012690608119697, 'p_nu': 12.0},
 {'p_m': -0.13276165859089117, 'p_lambda': 0.7678385849077702, 'p_nu': 12.0},
 {'p_m': 0.08202323328694752, 'p_lambda': 0.8090901115344494, 'p_nu': 12.0},
 {'p_m': -0.1485410658906876, 'p_lambda': 0.7588420653498217, 'p_nu': 12.0},
 {'p_m': 0.12123376991501882, 'p_lambda': 0.7982456026015521, 'p_nu': 12.0},
 {'p_m': 0.1105600956685007, 'p_lambda': 0.8017367211580925, 'p_nu': 12.0},
 {'p_m': 0.11613253763727473, 'p_lambda': 0.7999631073472214, 'p_nu': 12.0}]

In [16]:
[{'p_m': 0.42714721051663723, 'p_lambda': 0.5916276394259316, 'p_nu': 12.0},
 {'p_m': -0.10239176155884983, 'p_lambda': 0.7832639359232484, 'p_nu': 12.0},
 {'p_m': -0.1431752164114424, 'p_lambda': 0.7619717896431002, 'p_nu': 12.0},
 {'p_m': -0.05631194060649679, 'p_lambda': 0.8012690608119697, 'p_nu': 12.0},
 {'p_m': -0.13276165859089117, 'p_lambda': 0.7678385849077702, 'p_nu': 12.0},
 {'p_m': 0.08202323328694752, 'p_lambda': 0.8090901115344494, 'p_nu': 12.0},
 {'p_m': -0.1485410658906876, 'p_lambda': 0.7588420653498217, 'p_nu': 12.0},
 {'p_m': 0.12123376991501882, 'p_lambda': 0.7982456026015521, 'p_nu': 12.0},
 {'p_m': 0.1105600956685007, 'p_lambda': 0.8017367211580925, 'p_nu': 12.0},
 {'p_m': 0.11613253763727473, 'p_lambda': 0.7999631073472214, 'p_nu': 12.0}]

[{'p_m': 0.42714721051663723, 'p_lambda': 0.5916276394259316, 'p_nu': 12.0},
 {'p_m': -0.10239176155884983, 'p_lambda': 0.7832639359232484, 'p_nu': 12.0},
 {'p_m': -0.1431752164114424, 'p_lambda': 0.7619717896431002, 'p_nu': 12.0},
 {'p_m': -0.05631194060649679, 'p_lambda': 0.8012690608119697, 'p_nu': 12.0},
 {'p_m': -0.13276165859089117, 'p_lambda': 0.7678385849077702, 'p_nu': 12.0},
 {'p_m': 0.08202323328694752, 'p_lambda': 0.8090901115344494, 'p_nu': 12.0},
 {'p_m': -0.1485410658906876, 'p_lambda': 0.7588420653498217, 'p_nu': 12.0},
 {'p_m': 0.12123376991501882, 'p_lambda': 0.7982456026015521, 'p_nu': 12.0},
 {'p_m': 0.1105600956685007, 'p_lambda': 0.8017367211580925, 'p_nu': 12.0},
 {'p_m': 0.11613253763727473, 'p_lambda': 0.7999631073472214, 'p_nu': 12.0}]

In [17]:
learn_model.calc_pred_dist(x)

In [18]:
print(learn_model.get_p_params())

{'p_m': array([ 0.42714721, -0.10239176, -0.14317522, -0.05631194, -0.13276166,
        0.08202323, -0.14854107,  0.12123377,  0.1105601 ,  0.11613254]), 'p_lambda': array([0.59162764, 0.78326394, 0.76197179, 0.80126906, 0.76783858,
       0.80909011, 0.75884207, 0.7982456 , 0.80173672, 0.79996311]), 'p_nu': array([12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])}


In [19]:
y = np.empty((10,3))
y[:] = np.arange(3)
print(y)
learn_model._calc_pred_density(y)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


array([[0.28354178, 0.27076362, 0.14224127],
       [0.34426717, 0.21054385, 0.06656804],
       [0.33819723, 0.20314417, 0.0646226 ],
       [0.34927233, 0.21923442, 0.06946039],
       [0.33988008, 0.20500214, 0.06506828],
       [0.3504216 , 0.24539867, 0.0832551 ],
       [0.33729688, 0.20219589, 0.06440598],
       [0.34688245, 0.25207632, 0.08862568],
       [0.34800388, 0.25031889, 0.08710218],
       [0.34743275, 0.25124257, 0.08789194]])

In [20]:
for i in range(10):
    learn_model.calc_pred_dist(x[i])
    print(learn_model._calc_pred_density(np.arange(3)))


[0.28354178 0.27076362 0.14224127]
[0.34426717 0.21054385 0.06656804]
[0.33819723 0.20314417 0.0646226 ]
[0.34927233 0.21923442 0.06946039]
[0.33988008 0.20500214 0.06506828]
[0.3504216  0.24539867 0.0832551 ]
[0.33729688 0.20219589 0.06440598]
[0.34688245 0.25207632 0.08862568]
[0.34800388 0.25031889 0.08710218]
[0.34743275 0.25124257 0.08789194]


In [21]:
learn_model.calc_pred_dist(x)
print(learn_model.get_p_params())

{'p_m': array([ 0.42714721, -0.10239176, -0.14317522, -0.05631194, -0.13276166,
        0.08202323, -0.14854107,  0.12123377,  0.1105601 ,  0.11613254]), 'p_lambda': array([0.59162764, 0.78326394, 0.76197179, 0.80126906, 0.76783858,
       0.80909011, 0.75884207, 0.7982456 , 0.80173672, 0.79996311]), 'p_nu': array([12., 12., 12., 12., 12., 12., 12., 12., 12., 12.])}


In [22]:
pred_dist = learn_model.make_prediction(loss='KL')

In [24]:
pred_dist.pdf(y.T).T

array([[0.28354178, 0.27076362, 0.14224127],
       [0.34426717, 0.21054385, 0.06656804],
       [0.33819723, 0.20314417, 0.0646226 ],
       [0.34927233, 0.21923442, 0.06946039],
       [0.33988008, 0.20500214, 0.06506828],
       [0.3504216 , 0.24539867, 0.0832551 ],
       [0.33729688, 0.20219589, 0.06440598],
       [0.34688245, 0.25207632, 0.08862568],
       [0.34800388, 0.25031889, 0.08710218],
       [0.34743275, 0.25124257, 0.08789194]])

In [25]:
learn_model._calc_pred_density(y)

array([[0.28354178, 0.27076362, 0.14224127],
       [0.34426717, 0.21054385, 0.06656804],
       [0.33819723, 0.20314417, 0.0646226 ],
       [0.34927233, 0.21923442, 0.06946039],
       [0.33988008, 0.20500214, 0.06506828],
       [0.3504216 , 0.24539867, 0.0832551 ],
       [0.33729688, 0.20219589, 0.06440598],
       [0.34688245, 0.25207632, 0.08862568],
       [0.34800388, 0.25031889, 0.08710218],
       [0.34743275, 0.25124257, 0.08789194]])

In [ ]:
y

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [26]:
learn_model.calc_pred_dist(x)

In [27]:
learn_model._calc_pred_density(y)

array([[0.28354178, 0.27076362, 0.14224127],
       [0.34426717, 0.21054385, 0.06656804],
       [0.33819723, 0.20314417, 0.0646226 ],
       [0.34927233, 0.21923442, 0.06946039],
       [0.33988008, 0.20500214, 0.06506828],
       [0.3504216 , 0.24539867, 0.0832551 ],
       [0.33729688, 0.20219589, 0.06440598],
       [0.34688245, 0.25207632, 0.08862568],
       [0.34800388, 0.25031889, 0.08710218],
       [0.34743275, 0.25124257, 0.08789194]])

In [ ]:
learn_model._calc_pred_density(np.arange(10))

array([2.83541778e-01, 2.10543853e-01, 6.46225967e-02, 1.49772611e-02,
       2.81630649e-03, 6.53655584e-04, 1.21651326e-04, 3.36726126e-05,
       8.17436242e-06, 2.31787203e-06])