In [1]:
from bayesml import metatree,linearregression,normal,categorical
import numpy as np

In [2]:
rng = np.random.default_rng(12345)
n = 100
x_continuous = rng.random((n,5))
x_categorical = rng.choice([0,1], size=(n,5))
y_continuous = rng.random(n)
y_categorical = rng.choice([0,1], size=n)
print(x_continuous)
print(x_categorical)
print(y_continuous)
print(y_categorical)

[[2.27336022e-01 3.16758340e-01 7.97365457e-01 6.76254671e-01
  3.91109551e-01]
 [3.32813928e-01 5.98308754e-01 1.86734186e-01 6.72756044e-01
  9.41802865e-01]
 [2.48245715e-01 9.48881152e-01 6.67237453e-01 9.58979356e-02
  4.41839666e-01]
 [8.86479919e-01 6.97453500e-01 3.26472864e-01 7.33928163e-01
  2.20134956e-01]
 [8.15945695e-02 1.59895601e-01 3.40100185e-01 4.65193154e-01
  2.66421028e-01]
 [8.15776403e-01 1.93294389e-01 1.29469076e-01 9.16647515e-02
  5.98568014e-01]
 [8.54741904e-01 6.01621242e-01 9.31988361e-01 7.24781361e-01
  8.60551317e-01]
 [9.29337802e-01 5.46186009e-01 9.37672959e-01 4.94987940e-01
  2.73773182e-01]
 [4.51778707e-01 6.65038923e-01 3.30890930e-01 9.03454007e-01
  2.57074175e-01]
 [3.39828338e-01 2.58853399e-01 3.55446480e-01 5.02233372e-03
  6.28604544e-01]
 [2.82382707e-01 6.80876895e-02 6.16828977e-01 1.76326320e-01
  3.04388387e-01]
 [4.40886811e-01 1.50202341e-01 2.17928863e-01 4.74333115e-01
  4.76368855e-01]
 [2.55232354e-01 2.97565268e-01 2.790671

In [3]:
model = metatree.LearnModel(
    5,
    5,
    2,
    2,
    SubModel=linearregression,
    sub_constants={'c_degree':5},
    sub_h0_params={'h0_alpha':1.1},
)

In [4]:
model.update_posterior(
    x_continuous=x_continuous,
    x_categorical=x_categorical,
    y=y_continuous,
)

In [5]:
model.calc_pred_dist(
    x_continuous=x_continuous,
    x_categorical=x_categorical
)

In [6]:
model.make_prediction()

array([0.42007881, 0.50366392, 0.47933255, 0.6753799 , 0.22761597,
       0.36824984, 0.74157829, 0.65878129, 0.58030393, 0.25793044,
       0.22690517, 0.33172471, 0.28281002, 0.43174561, 0.52976617,
       0.47494249, 0.41679796, 0.5276337 , 0.4011753 , 0.33571743,
       0.28620828, 0.37491455, 0.47207639, 0.58797509, 0.35947639,
       0.53388011, 0.69674275, 0.67381498, 0.34711982, 0.33126557,
       0.60917885, 0.30828305, 0.76847853, 0.62390434, 0.65701356,
       0.24756356, 0.33842594, 0.54865111, 0.54308168, 0.40935857,
       0.32966369, 0.26530195, 0.22476758, 0.44699233, 0.38213012,
       0.74891684, 0.45907081, 0.58734159, 0.79910717, 0.33074651,
       0.46569306, 0.39028749, 0.54922718, 0.50672493, 0.55314738,
       0.29967801, 0.52011126, 0.60377733, 0.55770547, 0.48731611,
       0.50338459, 0.55700215, 0.64784981, 0.55907203, 0.28636007,
       0.59462345, 0.44631743, 0.30589707, 0.51527242, 0.4165508 ,
       0.39134732, 0.47711133, 0.44246378, 0.50112274, 0.46395

In [7]:
model.calc_pred_var()

array([0.10485877, 0.10869733, 0.10846459, 0.10666449, 0.10289831,
       0.10698252, 0.10600012, 0.10701322, 0.10571476, 0.10446855,
       0.10399942, 0.10354452, 0.10268688, 0.10546491, 0.10657629,
       0.10639984, 0.10542713, 0.10590318, 0.10915071, 0.10752073,
       0.10553026, 0.1027121 , 0.11010457, 0.10900768, 0.10364524,
       0.10616694, 0.10673081, 0.10756966, 0.10637735, 0.11282092,
       0.10633349, 0.108711  , 0.10506811, 0.11019747, 0.10761037,
       0.10799332, 0.10682618, 0.10706128, 0.10651878, 0.10443661,
       0.12533644, 0.10710598, 0.10884096, 0.10499781, 0.10846049,
       0.1068263 , 0.10553803, 0.10792317, 0.10533639, 0.10660191,
       0.10628983, 0.10558556, 0.10651597, 0.10987325, 0.1074153 ,
       0.10316387, 0.10798378, 0.11102336, 0.10915992, 0.11150669,
       0.10872581, 0.10650379, 0.10486375, 0.10548102, 0.10898809,
       0.10704292, 0.10589063, 0.10482028, 0.1049665 , 0.10988602,
       0.10692043, 0.10730181, 0.10914016, 0.10974576, 0.10568

In [8]:
model.calc_pred_density(np.arange(3)[:,np.newaxis])

array([[5.25464527e-01, 3.68065585e-01, 4.14501999e-01, 1.42408708e-01,
        9.67378576e-01, 6.42412918e-01, 9.07518006e-02, 1.58578798e-01,
        2.45871711e-01, 8.96815794e-01, 9.66635394e-01, 7.24670894e-01,
        8.41084840e-01, 5.02002790e-01, 3.22814672e-01, 4.18300729e-01,
        5.33514652e-01, 3.24573573e-01, 5.72398858e-01, 7.16308488e-01,
        8.30782418e-01, 6.22719301e-01, 4.31558919e-01, 2.43652280e-01,
        6.59543880e-01, 3.15102447e-01, 1.24403420e-01, 1.44392658e-01,
        6.89859980e-01, 7.25230277e-01, 2.10659313e-01, 7.77652512e-01,
        7.41965785e-02, 1.99309932e-01, 1.61625732e-01, 9.14034132e-01,
        7.10044928e-01, 2.94417840e-01, 3.01392187e-01, 5.47849011e-01,
        7.33228661e-01, 8.76629981e-01, 9.70463065e-01, 4.69810153e-01,
        6.10072786e-01, 8.81697719e-02, 4.46896172e-01, 2.42031667e-01,
        5.95875994e-02, 7.27604924e-01, 4.35502941e-01, 5.91374714e-01,
        2.92070580e-01, 3.65863854e-01, 2.88668898e-01, 8.007272