In [1]:
from bayesml import metatree,linearregression,normal,categorical
import numpy as np

In [2]:
rng = np.random.default_rng(12345)
n = 100
x_continuous = rng.random((n,5))
x_categorical = rng.choice([0,1], size=(n,5))
y_continuous = rng.random(n)
y_categorical = rng.choice([0,1], size=n)
print(x_continuous)
print(x_categorical)
print(y_continuous)
print(y_categorical)

[[2.27336022e-01 3.16758340e-01 7.97365457e-01 6.76254671e-01
  3.91109551e-01]
 [3.32813928e-01 5.98308754e-01 1.86734186e-01 6.72756044e-01
  9.41802865e-01]
 [2.48245715e-01 9.48881152e-01 6.67237453e-01 9.58979356e-02
  4.41839666e-01]
 [8.86479919e-01 6.97453500e-01 3.26472864e-01 7.33928163e-01
  2.20134956e-01]
 [8.15945695e-02 1.59895601e-01 3.40100185e-01 4.65193154e-01
  2.66421028e-01]
 [8.15776403e-01 1.93294389e-01 1.29469076e-01 9.16647515e-02
  5.98568014e-01]
 [8.54741904e-01 6.01621242e-01 9.31988361e-01 7.24781361e-01
  8.60551317e-01]
 [9.29337802e-01 5.46186009e-01 9.37672959e-01 4.94987940e-01
  2.73773182e-01]
 [4.51778707e-01 6.65038923e-01 3.30890930e-01 9.03454007e-01
  2.57074175e-01]
 [3.39828338e-01 2.58853399e-01 3.55446480e-01 5.02233372e-03
  6.28604544e-01]
 [2.82382707e-01 6.80876895e-02 6.16828977e-01 1.76326320e-01
  3.04388387e-01]
 [4.40886811e-01 1.50202341e-01 2.17928863e-01 4.74333115e-01
  4.76368855e-01]
 [2.55232354e-01 2.97565268e-01 2.790671

In [3]:
model = metatree.LearnModel(
    5,
    5,
    2,
    2,
    SubModel=linearregression,
    sub_constants={'c_degree':5},
    sub_h0_params={'h0_alpha':1.1},
)

In [4]:
model.update_posterior(
    x_continuous=x_continuous,
    x_categorical=x_categorical,
    y=y_continuous,
)

In [5]:
model.calc_pred_dist(
    x_continuous=x_continuous,
    x_categorical=x_categorical
)

In [6]:
model.make_prediction()

array([0.42019376, 0.50205301, 0.4795623 , 0.67536248, 0.22784666,
       0.36952465, 0.74151611, 0.65854664, 0.58031139, 0.25907802,
       0.22711721, 0.33256243, 0.28360408, 0.43168094, 0.5295982 ,
       0.47597363, 0.41666339, 0.52747734, 0.40130272, 0.33592086,
       0.28682612, 0.37514831, 0.47117565, 0.58758862, 0.35905455,
       0.53458388, 0.69748862, 0.6738692 , 0.34708731, 0.33065279,
       0.6098422 , 0.30829437, 0.76886957, 0.62136721, 0.65653091,
       0.2481373 , 0.33923474, 0.548755  , 0.54334707, 0.40984508,
       0.32730088, 0.26669416, 0.22419011, 0.44729339, 0.38135867,
       0.7488915 , 0.45972369, 0.58843365, 0.79954767, 0.33151884,
       0.46618047, 0.39078187, 0.55036753, 0.50522725, 0.55308793,
       0.30019117, 0.52049052, 0.60377583, 0.55881016, 0.48652601,
       0.50296263, 0.55693133, 0.64849052, 0.55932181, 0.28575972,
       0.59488249, 0.44627849, 0.3055406 , 0.51481122, 0.41637845,
       0.39196647, 0.47741524, 0.44275436, 0.49919943, 0.46492

In [7]:
model.calc_pred_var()

array([0.10485683, 0.11005865, 0.10846112, 0.10665858, 0.10288968,
       0.10702829, 0.10653222, 0.10701343, 0.10570938, 0.10456578,
       0.10380007, 0.10357399, 0.10273572, 0.10545838, 0.10658821,
       0.10641735, 0.10543419, 0.10590329, 0.10913589, 0.1074534 ,
       0.1055725 , 0.10271438, 0.1100962 , 0.10892915, 0.10364498,
       0.10619484, 0.10678949, 0.10793439, 0.1063528 , 0.11611115,
       0.10637919, 0.10954325, 0.10507023, 0.11206413, 0.10763367,
       0.107783  , 0.1068697 , 0.10704804, 0.10634426, 0.10443265,
       0.12656096, 0.10729688, 0.10341668, 0.10500045, 0.10951922,
       0.10681821, 0.10558551, 0.10793921, 0.10526559, 0.10669271,
       0.10766058, 0.1054566 , 0.10672491, 0.11190137, 0.10740977,
       0.10318668, 0.10799979, 0.11099233, 0.10924116, 0.11267927,
       0.10870978, 0.10642366, 0.10496763, 0.10547737, 0.10339542,
       0.10706094, 0.10588632, 0.10482045, 0.10497108, 0.10774728,
       0.10691699, 0.10766582, 0.10914608, 0.11149115, 0.10581

In [8]:
model.calc_pred_density(np.arange(3)[np.newaxis,:])

array([[5.25199599e-01, 2.44342263e-01, 2.08084799e-05],
       [3.70471939e-01, 3.82850893e-01, 1.09346239e-04],
       [4.14105801e-01, 3.42490273e-01, 6.88760345e-05],
       [1.42409958e-01, 7.41674236e-01, 4.83458377e-04],
       [9.66825228e-01, 6.88459380e-02, 1.50081704e-06],
       [6.39534507e-01, 1.87843035e-01, 1.34249466e-05],
       [9.15362511e-02, 8.96209519e-01, 9.38523358e-04],
       [1.58795719e-01, 7.03107889e-01, 4.11238397e-04],
       [2.45845247e-01, 5.27812600e-01, 1.54574648e-04],
       [8.94015361e-01, 8.91291240e-02, 2.51369794e-06],
       [9.66373382e-01, 6.98998761e-02, 1.58609637e-06],
       [7.22604373e-01, 1.42741986e-01, 6.28848888e-06],
       [8.39077201e-01, 1.01818724e-01, 2.86140237e-06],
       [5.02120532e-01, 2.61727837e-01, 2.53764935e-05],
       [3.23109237e-01, 4.27244454e-01, 9.18140266e-05],
       [4.16372214e-01, 3.31774190e-01, 4.71742060e-05],
       [5.33815905e-01, 2.41096519e-01, 2.14838283e-05],
       [3.24825741e-01, 4.21701